resources:
- name: ci
  type: git
  icon: github-circle
  source:
    uri: git@github.com:xtreme-nitin-ravindran/boring-kubernetes.git
    branch: master
    private_key: ((github_user_key))
    
- name: golang
  type: git
  icon: github-circle
  source:
    uri: git@github.com:golang/go.git
    branch: dev.boringcrypto.go1.14
    private_key: ((github_user_key))

- name: kubernetes
  type: git
  icon: github-circle
  source:
    uri: git@github.com:kubernetes/kubernetes.git
    tag_filter: v1.18.2
    private_key: ((github_user_key))

jobs:
- name: stuff
  plan:
  - in_parallel:
    - get: golang
    - get: ci
    - get: kubernetes
  - task: do stuff
    privileged: true
    file: ci/tasks/compile-golang/task.yml
